### ISSUE TITLE
[Device: Wiko TOMMY; Samsung J5] [Android 6.x - 7.x] OutOfMemoryError app crash

### ISSUE THREAD

**Issue by TrueMLGPro** [TrueMLGPro/Wi-Fi_Info#20]
```plain
[06-08 09:44:20.823 4290:4290 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.truemlgpro.wifiinfo, PID: 4290
java.lang.OutOfMemoryError: Failed to allocate a 170250316 byte allocation with 12578912 free bytes and 127MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
	at android.widget.ImageView.<init>(ImageView.java:152)
	at android.widget.ImageView.<init>(ImageView.java:140)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.truemlgpro.wifiinfo.SplashActivity.onCreate(SplashActivity.java:25)
	at android.app.Activity.performCreate(Activity.java:6372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2489)
	at android.app.ActivityThread.access$900(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:5430)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by TrueMLGPro** [comment]
### Solution: Add `android:largeHeap=true` in AndroidManifest.xml

**Comment by TrueMLGPro** [comment]
# Solved
