### ISSUE TITLE
[Android 11] Service crash on MainActivity

### ISSUE THREAD

**Issue by TrueMLGPro** [TrueMLGPro/Wi-Fi_Info#39]
```2021-02-16 21:08:19.655 5468-5468/com.truemlgpro.wifiinfo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.truemlgpro.wifiinfo, PID: 5468
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{71bf655 u0 com.truemlgpro.wifiinfo/.ConnectionStateService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by TrueMLGPro** [comment]
Fixed. Update with this fix comes out soon!
